### ISSUE TITLE
Retrieve more than 10k results from BSO

### ISSUE THREAD

**Issue by ericjeangirard** [dataesr/works-finder#11] opened 2023-09-28 14:09 UTC
Probably using the search-after param https://www.elastic.co/guide/en/elasticsearch/reference/current/paginate-search-results.html ?

**Comment by annelhote** [comment] 2023-09-28 14:11
Yes exactly, based on https://www.elastic.co/guide/en/elasticsearch/reference/current/point-in-time-api.html, I am currently on it as I did it in python before, it is "just" a translation task. But I will close this issue as it is a duplicate of #2

**Closed** 2023-09-28 14:12 UTC
